# Generated by Django 4.0.1 on 2022-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(upload_to='img/candidate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_pic',
            field=models.ImageField(upload_to='img/company'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='img/jobpost'),
        ),
    ]
