# Generated by Django 4.0.1 on 2022-01-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
