from django.db import models

# Create your models here.
class UserMaster(models.Model):

    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=50)
    otp = models.IntegerField()
    role = models.CharField(max_length=50)
    is_active = models.BooleanField(default = True)
    is_verified = models.BooleanField(default = False)
    is_created = models.DateTimeField(auto_now_add=True)
    is_updated = models.DateTimeField(auto_now_add=True)

class Candidate(models.Model):
    user_id = models.ForeignKey(UserMaster,on_delete=models.CASCADE)    
    firstname = models.CharField(max_length = 50)
    lastname = models.CharField(max_length = 50)
    contact = models.CharField(max_length = 50)
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    address = models.CharField(max_length = 150)
    dob = models.CharField(max_length = 50)
    gender = models.CharField(max_length = 50)
    min_salary = models.BigIntegerField(null=True)
    max_salary = models.BigIntegerField(null=True)
    job_type = models.CharField(max_length =150)
    country = models.CharField(max_length =150)
    highestedu = models.CharField(max_length =150)
    experience = models.CharField(max_length =150)
    website = models.CharField(max_length =150)
    shift = models.CharField(max_length =150)
    jobdescription = models.CharField(max_length =500)
    profile_pic = models.ImageField(upload_to="jobportal/img/candidate")

class Company(models.Model):
    user_id = models.ForeignKey(UserMaster,on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    company_name = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    contact = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    website = models.CharField(max_length=50)
    description = models.CharField(max_length =500)
    logo_pic = models.ImageField(upload_to="jobportal/img/company")

class JobDetails(models.Model):
    company_id = models.ForeignKey(Company,on_delete=models.CASCADE)
    jobname = models.CharField(max_length=250)
    companyname = models.CharField(max_length=250)
    companyaddress = models.CharField(max_length=250)
    jobdescription = models.TextField(max_length=500)
    qualification = models.CharField(max_length=255)
    responsibilities= models.CharField(max_length =500)
    location = models.CharField(max_length=255)
    companywebsite = models.CharField(max_length=255)
    companyemail = models.CharField(max_length=255)
    companycontact = models.CharField(max_length=25)
    salarypackage = models.CharField(max_length=255)
    experience = models.IntegerField()
    logo = models.ImageField(upload_to="jobportal/img/jobpost")

class ApplyList(models.Model):
    candidate = models.ForeignKey(Candidate,on_delete=models.CASCADE)
    job = models.ForeignKey(JobDetails,on_delete= models.CASCADE)
    education = models.CharField(max_length=200)
    experience = models.IntegerField()
    website = models.CharField(max_length=200)
    min_salary = models.CharField(max_length=200)
    max_salary = models.CharField(max_length=200)
    gender = models.CharField(max_length=200)
    resume = models.FileField(upload_to="jobportal/resume")